// <auto-generated />
using System;
using InitiativeScoping.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InitiativeScoping.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904114851_Disciplines")]
    partial class Disciplines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "und-u-ks-level2,und-u-ks-level2,icu,False")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ActualAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Hours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("ActualAdjustments");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ActualEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualsImportId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CalculatedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ExternalPersonId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalProjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Hours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("InitiativeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUnmapped")
                        .HasColumnType("boolean");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .UseCollation("case_insensitive");

                    b.Property<decimal?>("SourcedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ActualsImportId");

                    b.HasIndex("IsUnmapped");

                    b.HasIndex("PersonId");

                    b.HasIndex("SourceReference");

                    b.HasIndex("InitiativeId", "IsUnmapped", "WorkDate");

                    b.ToTable("ActualEntries");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ActualsImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Log")
                        .HasColumnType("text");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UnmappedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ActualsImports");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.AllocationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SizeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Method", "SizeKey")
                        .IsUnique();

                    b.ToTable("AllocationTemplates");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.AllocationTemplateLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AllocationTemplateId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Percent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Seniority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllocationTemplateId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("AllocationTemplateLines");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiffJson")
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("At");

                    b.HasIndex("Entity", "EntityId");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.BusinessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BusinessUnits");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ForecastBaseline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SnapshotBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId", "IsCurrent");

                    b.HasIndex("InitiativeId", "Version")
                        .IsUnique();

                    b.ToTable("ForecastBaselines");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ForecastBaselineLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ForecastBaselineId")
                        .HasColumnType("integer");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Hours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PhaseId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourcingClass")
                        .HasColumnType("integer");

                    b.Property<int>("Seniority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ForecastBaselineId");

                    b.ToTable("ForecastBaselineLines");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.Initiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SizeKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SizingMethod")
                        .HasColumnType("integer");

                    b.Property<string>("SponsoringTeam")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("TargetStart")
                        .HasColumnType("date");

                    b.Property<decimal?>("VarianceThresholdPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("Status");

                    b.ToTable("Initiatives");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.InitiativeAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractReference")
                        .HasColumnType("text");

                    b.Property<string>("CostCenter")
                        .HasColumnType("text");

                    b.Property<decimal>("EstimatedHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PhaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourcingClass")
                        .HasColumnType("integer");

                    b.Property<int>("Seniority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("InitiativeAllocations");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.InitiativeMember", b =>
                {
                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("InitiativeId", "UserId");

                    b.ToTable("InitiativeMembers");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.InitiativeSourceMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalProjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("Source", "ExternalProjectId")
                        .IsUnique();

                    b.ToTable("InitiativeSourceMappings");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalIds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourcingClass")
                        .HasColumnType("integer");

                    b.Property<int>("Seniority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("PlannedEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PlannedStart")
                        .HasColumnType("date");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.PhaseDateHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("NewEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NewStart")
                        .HasColumnType("date");

                    b.Property<DateOnly>("OldEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("OldStart")
                        .HasColumnType("date");

                    b.Property<int>("PhaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("PhaseDateHistories");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.RateCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EffectiveStart")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status", "EffectiveStart");

                    b.ToTable("RateCards");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.RateCardEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessUnitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .UseCollation("case_insensitive");

                    b.Property<int>("RateCardId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ResourcingClass")
                        .HasColumnType("integer");

                    b.Property<int>("Seniority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnitId");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("RateCardId", "ResourceTypeId", "BusinessUnitId", "Seniority", "Location", "ResourcingClass")
                        .IsUnique();

                    b.ToTable("RateCardEntries");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.RebaselineRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ResultingBaselineId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResultingBaselineId");

                    b.HasIndex("InitiativeId", "Status");

                    b.ToTable("RebaselineRequests");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ResourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .UseCollation("case_insensitive");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ResourceTypes");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.SizingConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Hours")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Method", "Key")
                        .IsUnique();

                    b.ToTable("SizingConversions");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ActualAdjustment", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.Initiative", "Initiative")
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ActualEntry", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.ActualsImport", "ActualsImport")
                        .WithMany("Entries")
                        .HasForeignKey("ActualsImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InitiativeScoping.Domain.Entities.Initiative", "Initiative")
                        .WithMany()
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InitiativeScoping.Domain.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActualsImport");

                    b.Navigation("Initiative");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.AllocationTemplateLine", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.AllocationTemplate", "AllocationTemplate")
                        .WithMany("Lines")
                        .HasForeignKey("AllocationTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InitiativeScoping.Domain.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AllocationTemplate");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ForecastBaseline", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Baselines")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ForecastBaselineLine", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.ForecastBaseline", "ForecastBaseline")
                        .WithMany("Lines")
                        .HasForeignKey("ForecastBaselineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForecastBaseline");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.Initiative", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessUnit");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.InitiativeAllocation", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Allocations")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InitiativeScoping.Domain.Entities.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InitiativeScoping.Domain.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Phase");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.InitiativeMember", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Members")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.InitiativeSourceMapping", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.Initiative", "Initiative")
                        .WithMany("SourceMappings")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.Person", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InitiativeScoping.Domain.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessUnit");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.Phase", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.Initiative", "Initiative")
                        .WithMany("Phases")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.PhaseDateHistory", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.Phase", "Phase")
                        .WithMany("DateHistory")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.RateCardEntry", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InitiativeScoping.Domain.Entities.RateCard", "RateCard")
                        .WithMany("Entries")
                        .HasForeignKey("RateCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InitiativeScoping.Domain.Entities.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessUnit");

                    b.Navigation("RateCard");

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.RebaselineRequest", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.Initiative", "Initiative")
                        .WithMany("RebaselineRequests")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InitiativeScoping.Domain.Entities.ForecastBaseline", "ResultingBaseline")
                        .WithMany()
                        .HasForeignKey("ResultingBaselineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Initiative");

                    b.Navigation("ResultingBaseline");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ResourceType", b =>
                {
                    b.HasOne("InitiativeScoping.Domain.Entities.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Discipline");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ActualsImport", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.AllocationTemplate", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.ForecastBaseline", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.Initiative", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Baselines");

                    b.Navigation("Members");

                    b.Navigation("Phases");

                    b.Navigation("RebaselineRequests");

                    b.Navigation("SourceMappings");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.Phase", b =>
                {
                    b.Navigation("DateHistory");
                });

            modelBuilder.Entity("InitiativeScoping.Domain.Entities.RateCard", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
